### ISSUE TITLE
Generate binary from parsed simulation data

### ISSUE THREAD

**Issue by adamsky** [adamsky/outcome#2]
The general idea would be to generate a binary from the specific set of data (e.g. a scenario with a set of modules involved).

There would be a set of rules for making Rust code representation of the data loaded by the parser. Rust code would be temporarily written to file and `cargo --build` would be run to create a binary. So this would already require rust and cargo present on the user  machine.

Functionality from `endgame` could be embedded into the binary to make it usable (interactive, server?).

Is this something worth investigating? It seems to me there could be some performance gain, but at this point I really don't know, never done anything like this.

For one thing [compile time static maps](https://github.com/sfackler/rust-phf) would likely be faster than regular runtime-loaded stuff.

**Comment by artrist** [comment]
I'm not sure if this sort of functionality would belong here in _outcome-sim_ or higher up in _endgame_. Or maybe split up somehow? 

Any application using outcome-sim could want to use this functionality, so it kind of makes sense to include it here. It would probably just be an interface for generating the Rust code to one giant string. The higher-up application could do the rest.

**Comment by adamsky** [comment]
After some initial testing I think there are some possible gains with codegen, not as many as I've initially hoped for though. Anyway I made a separate crate for that so this issue is not relevant here anymore.
